apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: walterarguello-xyz-tls
spec:
  secretName: walterarguello-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: walterarguello.xyz
  dnsNames:
    - walterarguello.xyz
    - www.walterarguello.xyz
