name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t waadmin/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true waadmin/react-test npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-353917

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: southamerica-west1-a

      - name: Build
        run: |-
          docker build -t waadmin/multi-client:latest -t waadmin/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t waadmin/multi-server:latest -t waadmin/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t waadmin/multi-worker:latest -t waadmin/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push waadmin/multi-client:latest
          docker push waadmin/multi-server:latest
          docker push waadmin/multi-worker:latest

          docker push waadmin/multi-client:${{ env.SHA }}
          docker push waadmin/multi-server:${{ env.SHA }}
          docker push waadmin/multi-worker:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=waadmin/multi-server:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=waadmin/multi-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=waadmin/multi-worker:${{ env.SHA }}
